name: monitoring
title: Monitoring
services:
  - name: cluster-agent
    title: Kubernetes cluster agent
    service: monitoring-cluster-agent

  - name: node-agent
    title: Kubernetes node agent
    service: monitoring-node-agent

  - name: node-exporter
    title: Node exporter
    service: monitoring-node-exporter

  - name: kube-state-metrics
    title: Kubernetes state metrics
    service: monitoring-kube-state-metrics
