name: monitoring
title: Monitoring
icon: metrics
services:
  - name: cluster-agent
    title: Kubernetes cluster agent
    service: cluster-agent

  - name: node-agent
    title: Kubernetes node agent
    service: node-agent

  - name: node-exporter
    title: Node exporter
    service: node-exporter

  - name: kube-state-metrics
    title: Kubernetes state metrics
    service: kube-state-metrics
